name         'camptocamp-mcollective'
version      '0.1.1'
source       'https://github.com/camptocamp/puppet-mcollective'
author       'DevOps Team / Camptocamp'
license      'GNU GPLv3'
summary      'Camptocamp MCollective Module'
description  'MCollective Module for Puppet'
project_page 'https://github.com/camptocamp/puppet-mcollective'

dependency  'puppetlabs/stdlib', '>= 3.2.x'
dependency  'ripienaar/concat', '>= 0.2.0'
dependency  'puppetlabs/rabbitmq', '>= 2.0.2'
dependency  'maestrodev/wget', '>= 1.1.x'
dependency 'puppetlabs/firewall', '>= 0.2.1'
